export interface WorkCategory {
  id: string;
  label: string;
  icon: string;
  subs: { id: string; label: string }[];
}

export const WORK_CATEGORIES: WorkCategory[] = [
  {
    id: 'renovation',
    label: 'Renovation & Remodeling',
    icon: '🏠',
    subs: [
      { id: 'Kitchen Renovation', label: 'Kitchen Renovation' },
      { id: 'Bathroom Renovation', label: 'Bathroom Renovation' },
      { id: 'Full House Renovation', label: 'Full House Renovation' },
      { id: 'Room Additions', label: 'Room Additions' },
      { id: 'Basement Finishing', label: 'Basement Finishing' },
      { id: 'Flooring', label: 'Flooring' },
      { id: 'Carpentry', label: 'Carpentry' },
      { id: 'Custom Cabinets', label: 'Custom Cabinets' },
      { id: 'Countertops', label: 'Countertops' },
      { id: 'Windows & Doors', label: 'Windows & Doors' },
      { id: 'Tile & Stone', label: 'Tile & Stone' },
      { id: 'Drywall', label: 'Drywall' },
      { id: 'Framing', label: 'Framing' },
    ],
  },
  {
    id: 'construction',
    label: 'Construction',
    icon: '🏗️',
    subs: [
      { id: 'ADU Construction', label: 'ADU Construction' },
      { id: 'Garage Conversion', label: 'Garage Conversion' },
      { id: 'New Construction', label: 'New Construction' },
      { id: 'Concrete', label: 'Concrete' },
      { id: 'Foundation Repair', label: 'Foundation Repair' },
      { id: 'Structural Repair', label: 'Structural Repair' },
      { id: 'Waterproofing', label: 'Waterproofing' },
      { id: 'Stucco', label: 'Stucco' },
      { id: 'Masonry & Brick', label: 'Masonry & Brick' },
      { id: 'Insulation', label: 'Insulation' },
      { id: 'Roofing', label: 'Roofing' },
      { id: 'Gutters', label: 'Gutters' },
      { id: 'Demolition', label: 'Demolition' },
    ],
  },
  {
    id: 'plumbing',
    label: 'Plumbing',
    icon: '🔧',
    subs: [
      { id: 'Plumbing', label: 'Plumbing' },
      { id: 'Drain Cleaning', label: 'Drain Cleaning' },
      { id: 'Sewer Repair', label: 'Sewer Repair' },
      { id: 'Water Heater', label: 'Water Heater' },
      { id: 'Tankless Water Heater', label: 'Tankless Water Heater' },
      { id: 'Leak Detection', label: 'Leak Detection' },
      { id: 'Repiping', label: 'Repiping' },
      { id: 'Water Filtration', label: 'Water Filtration' },
      { id: 'Gas Line Installation', label: 'Gas Line Installation' },
    ],
  },
  {
    id: 'electrical',
    label: 'Electrical',
    icon: '⚡',
    subs: [
      { id: 'Electrical', label: 'Electrical' },
      { id: 'EV Charger Installation', label: 'EV Charger Installation' },
      { id: 'Panel Upgrade', label: 'Panel Upgrade' },
      { id: 'Generator Installation', label: 'Generator Installation' },
      { id: 'Solar Installation', label: 'Solar Installation' },
      { id: 'Battery Backup Systems', label: 'Battery Backup Systems' },
      { id: 'Smart Home Systems', label: 'Smart Home Systems' },
      { id: 'Low Voltage Wiring', label: 'Low Voltage Wiring' },
      { id: 'Security Cameras', label: 'Security Cameras' },
      { id: 'Home Automation', label: 'Home Automation' },
    ],
  },
  {
    id: 'hvac',
    label: 'HVAC',
    icon: '❄️',
    subs: [
      { id: 'HVAC Installation', label: 'HVAC Installation' },
      { id: 'HVAC Repair', label: 'HVAC Repair' },
      { id: 'Air Conditioning', label: 'Air Conditioning' },
      { id: 'Heating Systems', label: 'Heating Systems' },
      { id: 'Ductwork', label: 'Ductwork' },
      { id: 'Ventilation', label: 'Ventilation' },
      { id: 'Indoor Air Quality', label: 'Indoor Air Quality' },
    ],
  },
  {
    id: 'exterior',
    label: 'Exterior & Landscaping',
    icon: '🌿',
    subs: [
      { id: 'Landscaping', label: 'Landscaping' },
      { id: 'Irrigation', label: 'Irrigation' },
      { id: 'Artificial Turf', label: 'Artificial Turf' },
      { id: 'Hardscape', label: 'Hardscape' },
      { id: 'Fencing', label: 'Fencing' },
      { id: 'Decks & Patios', label: 'Decks & Patios' },
      { id: 'Pergolas', label: 'Pergolas' },
      { id: 'Outdoor Kitchens', label: 'Outdoor Kitchens' },
      { id: 'Retaining Walls', label: 'Retaining Walls' },
      { id: 'Pool Construction', label: 'Pool Construction' },
      { id: 'Pool Repair', label: 'Pool Repair' },
      { id: 'Pool Service', label: 'Pool Service' },
      { id: 'Tree Service', label: 'Tree Service' },
      { id: 'Pressure Washing', label: 'Pressure Washing' },
      { id: 'Exterior Painting', label: 'Exterior Painting' },
    ],
  },
  {
    id: 'restoration',
    label: 'Restoration & Emergency',
    icon: '🚨',
    subs: [
      { id: 'Water Damage Restoration', label: 'Water Damage Restoration' },
      { id: 'Fire Damage Restoration', label: 'Fire Damage Restoration' },
      { id: 'Smoke Damage', label: 'Smoke Damage' },
      { id: 'Mold Remediation', label: 'Mold Remediation' },
      { id: 'Storm Damage Repair', label: 'Storm Damage Repair' },
      { id: 'Emergency Board-Up', label: 'Emergency Board-Up' },
      { id: 'Insurance Claim Repair', label: 'Insurance Claim Repair' },
      { id: 'Pest Control', label: 'Pest Control' },
      { id: 'Rodent Control', label: 'Rodent Control' },
      { id: 'Termite Treatment', label: 'Termite Treatment' },
      { id: 'Asbestos Removal', label: 'Asbestos Removal' },
      { id: 'Lead Paint Removal', label: 'Lead Paint Removal' },
    ],
  },
  {
    id: 'home_services',
    label: 'Home Services',
    icon: '🛠️',
    subs: [
      { id: 'Handyman', label: 'Handyman' },
      { id: 'Cleaning Services', label: 'Cleaning Services' },
      { id: 'Move-In / Move-Out Cleaning', label: 'Move-In / Move-Out Cleaning' },
      { id: 'Window Cleaning', label: 'Window Cleaning' },
      { id: 'Carpet Cleaning', label: 'Carpet Cleaning' },
      { id: 'Junk Removal', label: 'Junk Removal' },
      { id: 'Moving Services', label: 'Moving Services' },
      { id: 'Assembly Services', label: 'Assembly Services' },
      { id: 'TV Mounting', label: 'TV Mounting' },
      { id: 'Interior Painting', label: 'Interior Painting' },
      { id: 'Wallpaper Installation', label: 'Wallpaper Installation' },
      { id: 'Wallpaper Removal', label: 'Wallpaper Removal' },
      { id: 'Texture & Finishing', label: 'Texture & Finishing' },
      { id: 'Epoxy Flooring', label: 'Epoxy Flooring' },
      { id: 'Glass & Mirrors', label: 'Glass & Mirrors' },
      { id: 'Locksmith', label: 'Locksmith' },
      { id: 'Garage Door Repair', label: 'Garage Door Repair' },
      { id: 'Appliance Repair', label: 'Appliance Repair' },
      { id: 'Chimney Repair', label: 'Chimney Repair' },
      { id: 'Welding & Metal Work', label: 'Welding & Metal Work' },
    ],
  },
];

export const ALL_WORK_TYPES = WORK_CATEGORIES.flatMap(c => c.subs);

export function getCategoryForWork(workId: string): WorkCategory | undefined {
  return WORK_CATEGORIES.find(c => c.subs.some(s => s.id === workId));
}
